include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
      - custom_lint
  exclude:
    - 'build/**'
    - '**.freezed.dart'
    - '**.g.dart'

linter:
  rules:
    public_member_api_docs: false
    unnecessary_lambdas: false
    lines_longer_than_80_chars: false